version: '2'

services:
  base:
    image: node:10.4.0
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/

  install:
    extends:
      service: base
    working_dir: /usr/src/app/
    command: bash -c "npm install -g npm@5.7.1 && npm install"
